name: dart_httpproxy
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dotenv: ^4.0.1
  ffi: ^2.0.1
  http: ^0.13.5
  web_socket_channel: ^2.2.0
